-- MySQL Script generated by MySQL Workbench
-- Tue Jun 27 14:01:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nivelacesso` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contato` (
  `idcontato` INT NOT NULL AUTO_INCREMENT,
  `telefonecelular` VARCHAR(20) NULL,
  `telefoneresidencial` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  PRIMARY KEY (`idcontato`),
  UNIQUE INDEX `telefonecelular_UNIQUE` (`telefonecelular` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(20) NOT NULL,
  `logradouro` VARCHAR(50) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `cep` VARCHAR(10) NOT NULL,
  `referencia` VARCHAR(50) NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nomecliente` VARCHAR(50) NOT NULL,
  `cpfcliente` VARCHAR(15) NOT NULL,
  `rgcliente` VARCHAR(20) NOT NULL,
  `sexocliente` ENUM("Masculino", "Feminino") NOT NULL,
  `datanascimentocliente` DATE NOT NULL,
  `idendereco` INT NOT NULL,
  `idcontato` INT NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `cpfcliente_UNIQUE` (`cpfcliente` ASC) VISIBLE,
  UNIQUE INDEX `rgcliente_UNIQUE` (`rgcliente` ASC) VISIBLE,
  INDEX `fk_cliente_pk_contato_idx` (`idcontato` ASC) VISIBLE,
  INDEX `fk_cliente_pk_endereco_idx` (`idendereco` ASC) VISIBLE,
  INDEX `fk_cliente_pk_usuario_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_pk_contato`
    FOREIGN KEY (`idcontato`)
    REFERENCES `mydb`.`Contato` (`idcontato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_pk_endereco`
    FOREIGN KEY (`idendereco`)
    REFERENCES `mydb`.`Endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_pk_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `idCargo` INT NOT NULL,
  `titulocargo` VARCHAR(45) NOT NULL,
  `salario` DECIMAL(7,2) NOT NULL,
  `beneficio` VARCHAR(45) NOT NULL,
  `cargahoraria` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `idFuncionario` INT NOT NULL,
  `nomefuncionario` VARCHAR(20) NOT NULL,
  `datanascimentofuncionario` DATE NOT NULL,
  `sexofuncionario` ENUM("Masculino", "Feminino") NOT NULL,
  `cpffuncionario` VARCHAR(16) NOT NULL,
  `idcargo` INT NOT NULL,
  `cpffuncionario` VARCHAR(15) NOT NULL,
  `rgfuncionario` VARCHAR(25) NULL,
  `idendereco` INT NOT NULL,
  `idcontato` INT NOT NULL,
  `superior` VARCHAR(45) NOT NULL,
  `idusuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  INDEX `fk_funcionario_pk_contatos_idx` (`idcontato` ASC) VISIBLE,
  INDEX `fk_funcionario_pk_cargo_idx` (`idcargo` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_pk_contatos`
    FOREIGN KEY (`idcontato`)
    REFERENCES `mydb`.`Contato` (`idcontato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_pk_endereco`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Endereco` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_pk_cargo`
    FOREIGN KEY (`idcargo`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idfornecedor` INT NOT NULL,
  `razaosocial` VARCHAR(20) NOT NULL,
  `cnpj` VARCHAR(20) NOT NULL,
  `idendereco` VARCHAR(45) NOT NULL,
  `idcontato` VARCHAR(45) NOT NULL,
  `tipodeproduto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfornecedor`, `idendereco`),
  UNIQUE INDEX `razaosocial_UNIQUE` (`razaosocial` ASC) VISIBLE,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idcategoria` INT NOT NULL,
  `nomecategoria` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `descricaocategoria` TEXT NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lote` (
  `idLote` INT NOT NULL,
  `numerolote` VARCHAR(45) NOT NULL,
  `fabricacao` DATE NOT NULL,
  `validade` DATE NOT NULL,
  PRIMARY KEY (`idLote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idproduto` INT NOT NULL,
  `nomeproduto` VARCHAR(45) NOT NULL,
  `descricaoproduto` TEXT NOT NULL,
  `codigobarra` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(7,2) NOT NULL,
  `observacao` VARCHAR(45) NOT NULL,
  `idcategoria` INT NOT NULL,
  `idfornecedor` INT NOT NULL,
  `idlote` INT NOT NULL,
  PRIMARY KEY (`idproduto`),
  UNIQUE INDEX `codigobarra_UNIQUE` (`codigobarra` ASC) VISIBLE,
  INDEX `fk_produto_pk_categoria_idx` (`idcategoria` ASC) VISIBLE,
  INDEX `fk_produto_pk_lote_idx` (`idlote` ASC) VISIBLE,
  INDEX `fk_produto_pk_fornecedor_idx` (`idfornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_produto_pk_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `mydb`.`Categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_pk_lote`
    FOREIGN KEY (`idlote`)
    REFERENCES `mydb`.`Lote` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_pk_fornecedor`
    FOREIGN KEY (`idfornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idpedido` INT NOT NULL,
  `loja` VARCHAR(45) NOT NULL,
  `unidadeloja` VARCHAR(45) NOT NULL,
  `numeroprotocolo` VARCHAR(45) NOT NULL,
  `formapagamento` VARCHAR(45) NOT NULL,
  `parcelas` INT NOT NULL,
  `valorparcelas` DECIMAL(6,2) NOT NULL,
  `valortotalpedido` DECIMAL(7,2) NOT NULL,
  `datahora` DATE NOT NULL,
  `idfuncionario` INT NOT NULL,
  `idcliente` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  UNIQUE INDEX `numeroprotocolo_UNIQUE` (`numeroprotocolo` ASC) VISIBLE,
  INDEX `fk_pedido_pk_cliente_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_pk_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `mydb`.`Cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetalhePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DetalhePedido` (
  `iddetalhepedido` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `valortotal` DECIMAL(8,2) NOT NULL,
  `idpedidio` INT NOT NULL,
  `idproduto` INT NOT NULL,
  PRIMARY KEY (`iddetalhepedido`),
  INDEX `fk_detalhepedido_pk_pedido_idx` (`idpedidio` ASC) VISIBLE,
  CONSTRAINT `fk_detalhepedido_pk_pedido`
    FOREIGN KEY (`idpedidio`)
    REFERENCES `mydb`.`Pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalhepedido_pk_produto`
    FOREIGN KEY (`idpedidio`)
    REFERENCES `mydb`.`Produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
