-- MySQL Script generated by MySQL Workbench
-- Tue Jun 27 14:01:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema paperbook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema paperbook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `paperbook` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema dbsistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbsistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsistema` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `paperbook` ;

-- -----------------------------------------------------
-- Table `paperbook`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paperbook`.`Usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nivelacesso` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paperbook`.`Contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paperbook`.`Contato` (
  `idcontato` INT NOT NULL AUTO_INCREMENT,
  `telefonecelular` VARCHAR(20) NULL,
  `telefoneresidencial` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  PRIMARY KEY (`idcontato`),
  UNIQUE INDEX `telefonecelular_UNIQUE` (`telefonecelular` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paperbook`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paperbook`.`Endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(20) NOT NULL,
  `logradouro` VARCHAR(50) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `cep` VARCHAR(10) NOT NULL,
  `referencia` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paperbook`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paperbook`.`Cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nomecliente` VARCHAR(45) NOT NULL,
  `cpfcliente` VARCHAR(15) NOT NULL,
  `rgcliente` VARCHAR(45) NOT NULL,
  `sexocliente` ENUM("Masculino", "Feminino") NOT NULL,
  `datanascimentocliente` DATE NOT NULL,
  `idendereco` INT NOT NULL,
  `idcontato` INT NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `cpfcliente_UNIQUE` (`cpfcliente` ASC) ,
  UNIQUE INDEX `rgcliente_UNIQUE` (`rgcliente` ASC) ,
  INDEX `fk_cliente_pk_contato_idx` (`idcontato` ASC) ,
  INDEX `fk_cliente_pk_endereco_idx` (`idendereco` ASC) ,
  INDEX `fk_cliente_pk_usuario_idx` (`idusuario` ASC) ,
  CONSTRAINT `fk_cliente_pk_contato`
    FOREIGN KEY (`idcontato`)
    REFERENCES `paperbook`.`Contato` (`idcontato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_pk_endereco`
    FOREIGN KEY (`idendereco`)
    REFERENCES `paperbook`.`Endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_pk_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `paperbook`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paperbook`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paperbook`.`Cargo` (
  `idcargo` INT NOT NULL AUTO_INCREMENT,
  `titulocargo` VARCHAR(45) NULL,
  `salario` DECIMAL(7,5) NOT NULL,
  `beneficio` VARCHAR(45) NOT NULL,
  `cargahoraria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcargo`),
  UNIQUE INDEX `titulocargo_UNIQUE` (`titulocargo` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paperbook`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paperbook`.`Funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `nomefuncionario` VARCHAR(45) NOT NULL,
  `datanascimentofuncionario` DATE NOT NULL,
  `sexofuncionario` ENUM("Masculino", "Feminino") NOT NULL,
  `idcargo` INT NOT NULL,
  `cpffuncionario` VARCHAR(15) NOT NULL,
  `rgfuncionario` VARCHAR(45) NOT NULL,
  `idendereco` INT NOT NULL,
  `idcontato` INT NOT NULL,
  `superior` VARCHAR(45) NOT NULL,
  `idusuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  UNIQUE INDEX `cpffuncionario_UNIQUE` (`cpffuncionario` ASC) ,
  UNIQUE INDEX `rgfuncionario_UNIQUE` (`rgfuncionario` ASC) ,
  INDEX `fk_funcionario_pk_contato_idx` (`idcontato` ASC) ,
  INDEX `fk_cliente_pk_endereco_idx` (`idendereco` ASC) ,
  INDEX `fk_funcionario_pk_cargo_idx` (`idcargo` ASC) ,
  INDEX `fk_funcionario_pk_usuario_idx` (`idusuario` ASC) ,
  CONSTRAINT `fk_funcionario_pk_contato`
    FOREIGN KEY (`idcontato`)
    REFERENCES `paperbook`.`Contato` (`idcontato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_pk_endereco`
    FOREIGN KEY (`idendereco`)
    REFERENCES `paperbook`.`Endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_pk_cargo`
    FOREIGN KEY (`idcargo`)
    REFERENCES `paperbook`.`Cargo` (`idcargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_pk_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `paperbook`.`Usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paperbook`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paperbook`.`Fornecedor` (
  `idfornecedor` INT NOT NULL AUTO_INCREMENT,
  `razaosocial` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(20) NOT NULL,
  `idendereco` INT NOT NULL,
  `idcontato` INT NOT NULL,
  `tipodeproduto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfornecedor`),
  UNIQUE INDEX `razaosocial_UNIQUE` (`razaosocial` ASC) ,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paperbook`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paperbook`.`Categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `descricaocategoria` TEXT NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paperbook`.`Lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paperbook`.`Lote` (
  `idlote` INT NOT NULL AUTO_INCREMENT,
  `numerolote` VARCHAR(45) NOT NULL,
  `fabricacao` DATE NOT NULL,
  `validade` DATE NOT NULL,
  PRIMARY KEY (`idlote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paperbook`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paperbook`.`Produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nomeproduto` VARCHAR(45) NOT NULL,
  `descricaoproduto` TEXT NOT NULL,
  `codigobarras` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(7,2) NOT NULL,
  `observacao` VARCHAR(45) NOT NULL,
  `idcategoria` INT NOT NULL,
  `idfornecedor` INT NOT NULL,
  `idlote` INT NOT NULL,
  PRIMARY KEY (`idproduto`),
  UNIQUE INDEX `codigobarras_UNIQUE` (`codigobarras` ASC) ,
  INDEX `fk_produto_pk_categoria_idx` (`idcategoria` ASC) ,
  INDEX `fk_produto_pk_lote_idx` (`idlote` ASC) ,
  INDEX `fk_produto_pk_fornecedor_idx` (`idfornecedor` ASC) ,
  CONSTRAINT `fk_produto_pk_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `paperbook`.`Categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_pk_lote`
    FOREIGN KEY (`idlote`)
    REFERENCES `paperbook`.`Lote` (`idlote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_pk_fornecedor`
    FOREIGN KEY (`idfornecedor`)
    REFERENCES `paperbook`.`Fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paperbook`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paperbook`.`Pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `loja` VARCHAR(45) NOT NULL,
  `unidadeloja` VARCHAR(45) NOT NULL,
  `numeroprotocolo` VARCHAR(45) NOT NULL,
  `formapagamento` VARCHAR(45) NOT NULL,
  `parcelas` INT NOT NULL,
  `valorparcela` DECIMAL(6,2) NOT NULL,
  `valortotalpedido` DECIMAL(7,2) NOT NULL,
  `datahora` DATE NOT NULL,
  `idfuncionario` INT NOT NULL,
  `idcliente` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  UNIQUE INDEX `numeroprotocolo_UNIQUE` (`numeroprotocolo` ASC) ,
  INDEX `fk_pedido_pk_cliente_idx` (`idcliente` ASC) ,
  CONSTRAINT `fk_pedido_pk_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `paperbook`.`Cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paperbook`.`DetalhePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paperbook`.`DetalhePedido` (
  `iddetalhepedido` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `valortotal` DECIMAL(8,2) NOT NULL,
  `precounitario` DECIMAL(6,2) NOT NULL,
  `idpedido` INT NOT NULL,
  `idproduto` INT NOT NULL,
  PRIMARY KEY (`iddetalhepedido`),
  INDEX `fk_detalhepedido_pk_produto_idx` (`idproduto` ASC) ,
  INDEX `fk_detalhepedido_pk_pedido_idx` (`idpedido` ASC) ,
  CONSTRAINT `fk_detalhepedido_pk_produto`
    FOREIGN KEY (`idproduto`)
    REFERENCES `paperbook`.`Produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalhepedido_pk_pedido`
    FOREIGN KEY (`idpedido`)
    REFERENCES `paperbook`.`Pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `dbsistema` ;

-- -----------------------------------------------------
-- Table `dbsistema`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistema`.`clientes` (
  `idcli` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(9) NOT NULL,
  `cnpj` VARCHAR(14) NULL DEFAULT NULL,
  `endereco` VARCHAR(35) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(20) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cep` VARCHAR(20) NULL DEFAULT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `uf` CHAR(2) NULL DEFAULT NULL,
  `fone` VARCHAR(12) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idcli`),
  UNIQUE INDEX `cpf` (`cpf` ASC) ,
  UNIQUE INDEX `rg` (`rg` ASC) ,
  UNIQUE INDEX `email` (`email` ASC) ,
  UNIQUE INDEX `cnpj` (`cnpj` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbsistema`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistema`.`fornecedores` (
  `idfornecedor` INT NOT NULL AUTO_INCREMENT,
  `razaosocial` VARCHAR(50) NOT NULL,
  `nomefantasia` VARCHAR(50) NULL DEFAULT NULL,
  `cnpj` VARCHAR(14) NULL DEFAULT NULL,
  `logradouro` VARCHAR(35) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(20) NULL DEFAULT NULL,
  `cep` VARCHAR(20) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `referencia` VARCHAR(50) NULL DEFAULT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `uf` CHAR(2) NULL DEFAULT NULL,
  `telefone` VARCHAR(12) NULL DEFAULT NULL,
  `celular` VARCHAR(12) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idfornecedor`),
  UNIQUE INDEX `email` (`email` ASC) ,
  UNIQUE INDEX `cnpj` (`cnpj` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbsistema`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistema`.`produtos` (
  `codigoproduto` INT NOT NULL AUTO_INCREMENT,
  `barcode` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  `foto` LONGBLOB NOT NULL,
  `estoque` INT NULL DEFAULT NULL,
  `estoquemin` INT NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `medida` CHAR(2) NULL DEFAULT NULL,
  `armazenagem` VARCHAR(25) NOT NULL,
  `idfornecedor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codigoproduto`),
  UNIQUE INDEX `barcode` (`barcode` ASC) ,
  INDEX `idfornecedor` (`idfornecedor` ASC) ,
  CONSTRAINT `produtos_ibfk_1`
    FOREIGN KEY (`idfornecedor`)
    REFERENCES `dbsistema`.`fornecedores` (`idfornecedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbsistema`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistema`.`servicos` (
  `os` INT NOT NULL AUTO_INCREMENT,
  `dataOS` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `equipamento` VARCHAR(200) NOT NULL,
  `defeito` VARCHAR(200) NOT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `idcli` INT NOT NULL,
  PRIMARY KEY (`os`),
  INDEX `idcli` (`idcli` ASC) ,
  CONSTRAINT `servicos_ibfk_1`
    FOREIGN KEY (`idcli`)
    REFERENCES `dbsistema`.`clientes` (`idcli`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbsistema`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistema`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `login` VARCHAR(15) NOT NULL,
  `senha` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login` (`login` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
